# Generated by Django 4.0.4 on 2022-12-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='v_cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=20)),
                ('book_pic', models.ImageField(upload_to='static/book_images/')),
                ('book_price', models.FloatField()),
                ('cart_uid', models.IntegerField()),
                ('cart_bid', models.IntegerField()),
                ('cart_num', models.IntegerField()),
            ],
            options={
                'db_table': 'cart_book_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='t_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_uid', models.IntegerField(default=0)),
                ('order_name', models.CharField(max_length=30)),
                ('order_address', models.CharField(max_length=100)),
                ('order_tel', models.CharField(max_length=20)),
                ('order_payment', models.CharField(max_length=10)),
                ('order_status', models.CharField(max_length=10)),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('order_valid', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='t_orderitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_oid', models.IntegerField()),
                ('order_bid', models.IntegerField()),
                ('order_num', models.IntegerField()),
            ],
        ),
    ]
