# Generated by Django 4.0.4 on 2022-12-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='t_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=20)),
                ('book_pic', models.ImageField(upload_to='static/book_images/')),
                ('book_author', models.CharField(max_length=50)),
                ('book_price', models.FloatField()),
                ('book_info', models.TextField()),
                ('book_isbn', models.CharField(max_length=15)),
                ('book_press', models.CharField(max_length=30)),
                ('book_date', models.DateField()),
                ('book_num', models.IntegerField(default=10)),
            ],
        ),
    ]
